# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=40)),
                ('car_status', models.CharField(choices=[('0', '空置'), ('1', '取料'), ('2', '装料'), ('3', '送料'), ('4', '完成'), ('5', '无任务返回原点')], default='0', max_length=10)),
                ('default_mark', models.CharField(default='', max_length=40)),
                ('distination', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('error_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=40)),
                ('error_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=40)),
                ('goods_type', models.CharField(max_length=40)),
                ('goods_counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Line_warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_status', models.CharField(default='0', max_length=40)),
                ('start_time', models.CharField(default='', max_length=40)),
                ('end_time', models.CharField(default='', max_length=40)),
                ('total_time', models.CharField(default='', max_length=40)),
                ('line_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.CharField(max_length=30)),
                ('mark_status', models.CharField(default='0', max_length=30)),
                ('next_mark', models.CharField(default='', max_length=30)),
                ('line_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Line')),
            ],
            options={
                'ordering': ['mark_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=40)),
                ('order_time', models.CharField(max_length=40)),
                ('order_status', models.CharField(default='未完成', max_length=40)),
                ('different_car', models.CharField(blank=True, default='', max_length=40)),
                ('finish_time', models.CharField(blank=True, default='', max_length=40)),
                ('total_time', models.CharField(blank=True, default='', max_length=40)),
                ('work_type', models.CharField(blank=True, default='', max_length=40)),
                ('car_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Car')),
                ('line_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Order_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.IntegerField(default=0)),
                ('order_status', models.CharField(default='0', max_length=40)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Goods')),
                ('order_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('station_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Mark')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Station'),
        ),
        migrations.AddField(
            model_name='line_warn',
            name='line_station',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Station'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_line',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Line'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Station'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Mark'),
        ),
        migrations.AddField(
            model_name='car',
            name='line_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Line'),
        ),
    ]
