# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='Description',
            field=models.CharField(default='', max_length=120),
        ),
    ]
